{% set name = "PyLBFGS" %}
{% set version = "0.2.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01b05e381eafaba873453222af527eeb29b2b44771c4523917bd956403e6ceb7

build:
  skip: true  # [win]
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - lbfgs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dedupeio/pylbfgs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LBFGS and OWL-QN optimization algorithms
  description: |
    This is a Python wrapper around Naoaki Okazaki (chokkan)'s
    liblbfgs library of quasi-Newton optimization routines (limited
    memory BFGS and OWL-QN).
  doc_url: https://github.com/dedupeio/pylbfgs
  dev_url: https://github.com/dedupeio/pylbfgs

extra:
  recipe-maintainers:
    - beckermr
