travis:
  secure:
    BINSTAR_TOKEN: JW9zzEppftGRVrHAMmg/eL2AAiayIR4Rkss1K8oYc4OAQ+oceG8+ZLFWtHXwrhJgDP/YMln2L+M+J/h2gFj6CYcHmtSeaI3JTPhJxhTTzGZb+lUD+47QdLEM2ql8fox+0ZdTgiw4jA3jtnS/YPwdlY7ZXj5JGnuHzTl00LU5v8OorqWFTrLSBNCNa3FsqnG2mxzMuFAXFDU0HUIanBylyGxObNIXWqjlFr2rbKVCVrkb78A8c1gYr7/wfzi1SpdlPavzpiudN0zffC2k9Ts15sn4lncOzJm10S/ZOnO9SSu5sDFwIocvuhMmRg1YIMLUemioroWmmQYyQaInluWa/1+8x6L/6OTf1npcDRDk2ccm2jCw6P2cN/XZItmJqE2jkKtDW7tf2hzZww2a3aeXzgGCHU74xSqcXGefleBlq1T9p8ntE8wivFqBHnyxzSLaPog1kSSAx+JxKwLuizeHGvjGvV2nopTak69iF6avO2JS8Bi4JgS6Q4U9h/DQA+ZK0CT40rVz/NdhkHruL+nAbUC+P9MKNNtEDUeu4lrY6Ajpnxuo8soafxOE8Hpbgs39u0K0gUBvBI0z+Cj6HjtjkC5yTSmeCOXuWw5FKYXLzQg52hr2Lq1jOvYB+MLfzwyHD6gDC6HbTQOAYj7nohEAtr6JnhuL5AHzOnKxGQOJy4c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
